version: "3"
services:
   wordpress:
     image: wordpress
     ports: 
        - "8085:80"
     depends_on: 
       - mysql
     environment:
       WORDPRESS_DB_HOST: mysql
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: "hello"
       WORDPRESS_DB_NAME: wordpress
   mysql:
     image: "mysql:5.7"  
     environment:
       MYSQL_DATABASE: wordpress
       MYSQL_ROOT_PASSWORD: "hello"
     volumes:
       - ./mysql:/users/lawre/OneDrive/Documents/Docker/vpcpy/Docker/compose1
networks:
  youknow:
     ipam:
        driver: default
        config:
          - subnet: "192.168.56.0/24"
 